---
title: 'Mini Project #3'
author: "Vivian Wang, Maggie Wang"
date: "November 13, 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mdsr)
library(RMySQL)
library(dplyr)
library(ggplot2)
library(ggthemes)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
sequelinter_sql <- "
SELECT t.id AS sequel_id, t.title,
	t.production_year AS sequel_year, 
	MAX(t2.production_year) AS prev_year
FROM title t
JOIN movie_link ml ON ml.movie_id = t.id
JOIN title t2 ON t2.id = ml.linked_movie_id
JOIN movie_info mi ON mi.movie_id = t.id
JOIN movie_info mi2 ON mi2.movie_id = t.id
JOIN movie_info mi3 ON mi3.movie_id = t.id
WHERE t.kind_id = 1
AND ml.link_type_id IN (1,3)
AND mi.info_type_id = 1
AND mi.info > 60
AND mi2.info_type_id = 3
AND mi2.info NOT LIKE '%Adult%'
AND mi3.info_type_id = 8
AND mi3.info LIKE '%USA%'
GROUP BY t.id;
"
sequelinter <- db %>% 
  dbGetQuery(sequelinter_sql)
```

```{r}
sequelinter <- sequelinter %>% 
  mutate(interval = sequel_year - prev_year) %>% 
  filter(interval >= 0 & sequel_year <= 2017)
```

```{r}
sequel_year <- sequelinter %>% 
  group_by(sequel_year) %>% 
  summarize(num_sequel = n())

sequel_year %>% ggplot(aes(x = sequel_year, y = num_sequel)) + 
  annotate("rect", xmin = 1929, xmax = 1960, ymin = -Inf, ymax = Inf, 
           fill = "darkgoldenrod3", alpha = 0.2) + 
  geom_text(data = NULL, aes(x = 1945, y = 140), label = "Golden Age of\nHollywood") + 
  geom_bar(stat = "identity", fill = "royalblue4") + 
  theme_economist_white() + 
  scale_x_continuous(name = "Year", 
                     breaks = c(1910, 1920, 1930, 1940, 1950, 1960, 
                                1970, 1980, 1990, 2000, 2010)) + 
  scale_y_continuous(name = "Number of\nSequels/Remakes/Reboots", 
                     breaks = c(0, 25, 50, 75, 100, 125))
  
```


```{r}


sequelinter %>% ggplot(aes(x = sequel_year, y = interval)) + 
  geom_point(alpha = 0.2, position = "jitter") + 
  theme_economist_white() + 
  scale_x_continuous(name = "Year", 
                     breaks = c(1910, 1920, 1930, 1940, 1950, 1960, 
                                1970, 1980, 1990, 2000, 2010)) + 
  scale_y_continuous(name = "Years from\nLast Film", 
                     breaks = c(0, 25, 50, 75, 100, 125)) + 
  geom_segment(aes(x = 2017, y = 0, xend = 2017, yend = 85), 
               color = "royalblue4", size = 1.2) + 
  geom_segment(aes(x = 1975, y = 0, xend = 1975, yend = 49), 
               color = "royalblue4", size = 1.2) + 
  geom_segment(aes(x = 1930, y = 0, xend = 1930, yend = 15), 
               color = "royalblue4", size = 1.2) + 
  geom_segment(aes(x = 1910, y = 10, xend = 2017, yend = 100), color = "royalblue4",
               arrow = arrow(angle = 15, length = unit(0.2, "inches"), type = "closed"))
```

